const topicDisplayName: Record<string, string> = {
  // Front-end
  html: 'HTML',
  html5: 'HTML5',
  css: 'CSS',
  css3: 'CSS3',
  javascript: 'JavaScript',
  js: 'JavaScript',
  typescript: 'TypeScript',
  ts: 'TypeScript',
  tsx: 'TSX',
  react: 'React',
  reactjs: 'React',
  'react-js': 'React',
  'react-native': 'React Native',
  'react-router': 'React Router',
  'react-router-dom': 'React Router',
  reactrouter: 'React Router',
  nextjs: 'Next.js',
  nextjs15: 'Next.js 15',
  'next-js': 'Next.js',
  next: 'Next.js',
  tailwind: 'Tailwind CSS',
  tailwindcss: 'Tailwind CSS',
  'tailwind-css': 'Tailwind CSS',
  nativewind: 'NativeWind',
  'react-query': 'React Query',
  reactquery: 'React Query',
  'reactquery-v3': 'React Query',
  tanstack: 'TanStack',
  '@tanstack/react-query': 'TanStack Query',
  '@tanstack/react-router': 'TanStack Router',
  'tanstack-router': 'TanStack Router',
  'tanstack-query': 'TanStack Query',
  redux: 'Redux',
  'react-redux': 'Redux',
  shadcn: 'shadcn/ui',
  'shadcn-ui': 'shadcn/ui',
  shadcnui: 'shadcn/ui',
  vite: 'Vite',
  vitejs: 'Vite',
  webpack: 'Webpack',
  zod: 'Zod',
  'react-hook-form': 'React Hook Form',
  'react-hooks-form': 'React Hook Form',
  rhf: 'React Hook Form',
  radix: 'Radix UI',
  'radix-ui': 'Radix UI',
  '@radix-ui': 'Radix UI',
  'styled-components': 'Styled Components',
  styledcomponents: 'Styled Components',
  babel: 'Babel',
  shiki: 'Shiki',
  nuqs: 'nuqs',
  lucide: 'Lucide',
  'lucide-react': 'Lucide',
  'lucide-react-native': 'Lucide',
  ionicons: 'Ionicons',
  'ion-icons': 'Ionicons',
  // Back-end & Databases
  node: 'Node.js',
  nodejs: 'Node.js',
  'node-js': 'Node.js',
  nestjs: 'NestJS',
  nest: 'NestJS',
  express: 'Express',
  expressjs: 'Express',
  'express-js': 'Express',
  fastify: 'Fastify',
  mysql: 'MySQL',
  sql: 'SQL',
  mongodb: 'MongoDB',
  mongo: 'MongoDB',
  prisma: 'Prisma',
  drizzle: 'Drizzle',
  'drizzle-orm': 'Drizzle ORM',
  postgresql: 'PostgreSQL',
  postgres: 'PostgreSQL',
  pg: 'PostgreSQL',
  java: 'Java',
  poo: 'OOP',
  laravel: 'Laravel',
  php: 'PHP',
  csharp: 'C#',
  'c#': 'C#',
  rabbitmq: 'RabbitMQ',
  'rabbit-mq': 'RabbitMQ',
  // Tools & Libraries
  clerk: 'Clerk',
  eslint: 'ESLint',
  biomejs: 'Biome',
  biome: 'Biome',
  prettier: 'Prettier',
  turborepo: 'Turborepo',
  t3: 'T3',
  't3-env': 'T3 Env',
  't3-stack': 'T3 Stack',
  fakerjs: 'Faker.js',
  faker: 'Faker.js',
  ultracite: 'Ultracite',
  cypress: 'Cypress',
  typeorm: 'TypeORM',
  jwt: 'JWT',
  jsonwebtoken: 'JWT',
  'date-fns': 'date-fns',
  datefns: 'date-fns',
  dayjs: 'Day.js',
  'day-js': 'Day.js',
  vitest: 'Vitest',
  swagger: 'Swagger',
  'swagger-ui': 'Swagger UI',
  // Mobile & Native
  expo: 'Expo',
  android: 'Android',
  'android-studio': 'Android Studio',
  // Cloud & DevOps
  vercel: 'Vercel',
  aws: 'AWS',
  'aws-lambda': 'AWS Lambda',
  serverless: 'Serverless',
  'serverless-framework': 'Serverless',
  'serverless-offline': 'Serverless Offline',
  azure: 'Azure',
  firebase: 'Firebase',
  git: 'Git',
  docker: 'Docker',
  'docker-compose': 'Docker Compose',
  dockerfile: 'Dockerfile',
  // IDEs & Editors
  'visual-studio': 'Visual Studio',
  visualstudio: 'Visual Studio',
  vs: 'Visual Studio',
  microsoft: 'Visual Studio',
  vscode: 'VS Code',
  'vs-code': 'VS Code',
  'visual-studio-code': 'VS Code',
  'microsoft-visual-studio-code': 'VS Code',
}

function toTitleCase(str: string): string {
  return str
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

export function getTopicDisplayName(topic: string): string {
  const normalized = topic.toLowerCase().trim()
  return topicDisplayName[normalized] ?? toTitleCase(normalized)
}
